### ISSUE TITLE
df_financial does not seem to contain NFCI data

### ISSUE THREAD

**Issue by mrpg** [onnokleen/mfGARCH#10]
The _df_financial_ data set contains the following first five values of _nfci_ (starting Jan 8, 1971): 0.41, 0.45, 0.50, 0.55, 0.60. However, [NFCI as published by the Federal Reserve Bank of Chicago](https://fred.stlouisfed.org/series/NFCI) has the following first five values (starting Jan 8, 1971): 0.46, 0.50, 0.54, 0.59, 0.63. Therefore, _df_financial_ does not seem to contain NFCI data, but some other (similar) time series.

Example:

`library(alfred)`
`nfci <- get_fred_series("NFCI", "nfci")`
`head(nfci$nfci)`

`library(mfGARCH)`
`head(unique(df_financial$nfci))`

These two code snippets give very different outputs.

**Comment by onnokleen** [comment]
The NFCI is an index which is standardized on an increasing window. That's why it's changing also previous releases with each current release.
