### ISSUE TITLE
qustion about residuals(NA)

### ISSUE THREAD

**Issue by shadowzhc** [onnokleen/mfGARCH#12]
why the "df.fitted"'s residuals are NA?

**Comment by shadowzhc** [comment]
Besides, the "g" and "tau" in "df.fitted" are also NA, and I am confused. 
and all above are from the dataset "df.finance" in example code.

**Comment by onnokleen** [comment]
It's because of the lagged covariates. The first returns don't have residuals until there are enough lags of the covariate available to calculate them.

**Comment by shadowzhc** [comment]
Thank a lot for replying!

**Comment by shadowzhc** [comment]
Hi, onnokleen!
I have one more question: In your package mfGARCH, what kind of distribution does the standared residual(also called i.i.d innovation) assume(obey) ?
Best wishes! 
Zhu

**Comment by onnokleen** [comment]
The estimation is carried out via quasi-maximum likelihood.
