### ISSUE TITLE
How could I calculate the VaR(Value-at-Risk) from the model?

### ISSUE THREAD

**Issue by shadowzhc** [onnokleen/mfGARCH#13]
Hi, onnokleen!
   The question is : From the package "rugarch", we can calculate VaR by the formalu VaR=cond.mean + cond.sigma * qdist(...), and the code is ( quantile(ugarchfit,0.05) ). 
  I am wondering how can I get the VaR from your package?
  All the best,
  Zhu.

**Comment by onnokleen** [comment]
You can use that formula also with an mfGARCH object. Just take the square-root of the variance forecast from predict(...) times the alpha quantile from the residuals + adding the estimated mean.
