### ISSUE TITLE
#1How to perform a Likelihood ratio test? #2 predict() function 

### ISSUE THREAD

**Issue by woozie2** [onnokleen/mfGARCH#14]
Hi onnokleen,

First, I'd like to perform a likelihood ratio test for determining whether to use a restricted or unrestricted weighting scheme. The test should have the form [2*(L(ur) - L(r)] where L(ur) and L(r) refer to the likelihood of the respective Garch-Midas model with unrestricted and restricted weights. Especially I'm interested in the p-values. Using just the max llh values does in my eyes not work.  
#in R
     teststat <- -2 * (as.numeric(unr)-as.numeric(r))
     p.val <- pchisq(teststat, df = 2, lower.tail = FALSE)
     p.val

Second, the output of the predict() function always has a vector of ten increasing values. Do these reflect the ten steps ahead predictions? But if I want to change something, f.e. n.ahead = 2, there is in fact no change. Do I have to specify anything differently?
#in R
    mfg_fit <- fit_mfgarch()
    predict(mfg_fit, n.ahead = 2, newdata=x)

Thank you in advance!

**Comment by onnokleen** [comment]
Please provide a minimal reproducible example, see (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by woozie2** [comment]
Hopefully, the code is in an appropriate manner displayed. I'm using the data frame df_financial from the package mfGARCH. 

`library(mfGARCH)  
#1#likelihood ratio test  
#GARCH model with restricted and unrestricted weighting schemes  

r_mfgarch <- fit_mfgarch(data = df_financial,  
                             y = "return",  
                             x = "nfci",  
                             low.freq = "week",  
                             K = 52,  
                             weighting = "beta.restricted")  

unr_mfgarch <- fit_mfgarch(data = df_financial,  
                         y = "return",  
                         x = "nfci",  
                         low.freq = "week",  
                         K = 52,  
                         weighting = "beta.unrestricted")  

#taking max loglikelihood values
r <- r_mfgarch$llh  
unr <- un_mfgarch$llh  
#actual test
teststat <- -2 * (as.numeric(r)-as.numeric(unr))  
p.val <- pchisq(teststat, df = 1, lower.tail = FALSE)  
p.val #rejection of null hypotheses -> using restricted   

#2#predict function, different versions, same problem  
#version1  
fit_predict1 <- predict(r_mfgarch, n.ahead = 2)  

#version2  
fit_predict2 <- predict(r_mfgarch, horizon = c(1:2),  
                       fcts.tau = NULL,  
                       y.last = NULL,  
                       cond.var = NULL,  
                       cond.tau = NULL)  
#version3  
is <- df_financial[1:400,]  
os <- df_financial[401:421,]  

r_mfgarch_is <- fit_mfgarch(data = is,  
                         y = "return",  
                         x = "nfci",  
                         low.freq = "week",  
                         K = 52,  
                         weighting = "beta.restricted")  
fit_predict3 <- predict(r_mfgarch_is, n.ahead = 2, newdata = os)`

**Comment by onnokleen** [comment]
Thanks!
1) I do not get what your problem with the LR test is? However, I get a p-value of 0.68. Hence, no rejection of the null hypothesis.
2) predict.mfGARCH has no n.ahead argument but only horizon. Moreover, it does not have a newdata argument as of now. You have to program that part of the forecasting yourself. The current version can only calculate forecasts that are consecutive to the estimation period.
