### ISSUE TITLE
How to handle RV when return is multiplied by 100

### ISSUE THREAD

**Issue by gxygogo** [onnokleen/mfGARCH#15]
Hi onnokleen,
  
     Thanks for your impressive work! But I am a little confused of something. According to the code, I am suggested to multiply the return by 100. I wonder when I use realized volatility, that is, the sum of squared daily return in a month, as the low-frequency variable, should I apply the realized volatility calculated from the original return series or multiply it by 10000. 

Thanks again!

**Comment by onnokleen** [comment]
You can try it out but my take would be to multiply by 10.000 as you said.

**Comment by gxygogo** [comment]
Thanks professor. I still wonder should I take log for the RV after multiplying it by 10.000
