### ISSUE TITLE
How can I use mfgarch to one-step-ahead forecast the volatility?

### ISSUE THREAD

**Issue by ErwanPishi** [onnokleen/mfGARCH#18]
I'm writing my master thesis. Today I read the mfgarch document on CRAN, but only to find there is no method to do one-step ahead forecasting. If you could give me some guidance, I would greatly appreciate it.

**Comment by onnokleen** [comment]
predict() is your friend.

**Comment by ErwanPishi** [comment]
Wow！it works！I was not familiar with R. Thank you！
