### ISSUE TITLE
Error in data.frame: arguments imply differing number of rows

### ISSUE THREAD

**Issue by joanameta** [onnokleen/mfGARCH#3]
While fitting midas-garch model to the data using the fit_mfgarch function from mfGARCH package I encountered the following errror message:

![error message](https://user-images.githubusercontent.com/23406366/48680857-0cb02d00-eb9f-11e8-9fe2-6c0211ac065f.JPG)

Apparently the trouble was caused by na.locf(X) function used to fill in values of the variable with lower frequency. Using na.locf(X, fromLast = TRUE) instead of the aforementioned command solves the issue. However, the end of the data.frame must be checked as the lack of last value may result in NAs. They should be taken care of separately given the function does not accept not available values.

Thank you @onnokleen for your professional assistance!

The following tables demonstrate the reason for the code break as well as how the correct data should look like:

![wrong](https://user-images.githubusercontent.com/23406366/48680802-a5927880-eb9e-11e8-866d-eaa24699e35a.png) 

![correct](https://user-images.githubusercontent.com/23406366/48680812-b642ee80-eb9e-11e8-9c7b-4c4a398c05a5.png)

**Comment by onnokleen** [comment]
already committed - warning will be part of next release
