### ISSUE TITLE
Date format issue

### ISSUE THREAD

**Issue by aima21** [onnokleen/mfGARCH#8]
Hi !

I have carefully formatted the date column as date however I keep getting the following error:

 Supplied date column is not of format 'Date'.

Does the GARCH-MIDAS package have a specific date format?

Thanks

**Comment by onnokleen** [comment]
Do you have an example? Do you use as.Date?

**Comment by aima21** [comment]
Hi ! 

Yes I have, but another error I get is:

Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 134, 141

Even though the number of rows and is equal in all variables. 

Thanks

**Comment by onnokleen** [comment]
My first guess is that your data is not properly organized, see Issue #3

**Comment by aima21** [comment]
Hello!

The last issue was resolved. My next issue is to find out if I can use high frequency intraday data versus daily data. If so will the function accept time stamps?

Kind Regards,
Aima

**Comment by onnokleen** [comment]
Hi Aima,

it is built for daily data. If it works with intraday data, you should be cautious about the results.

**Comment by aima21** [comment]
Thank you for your reply.

Best Wishes,
Aima
________________________________
